apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.encryption.sensitivePropertiesKey.secretRef.name }}
data:
{{- range .Values.global.secret.sensitivePropertiesData.entries }}
  {{ .key }}: {{ .value | b64enc }}
{{- end }}
type: Opaque
