{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chart.fullname" . }}-pdb
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . }}
      release: {{ .Release.Name }}
{{- end }}
