{{- if .Values.pdb.zookeeper.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zookeeper.name" . }}-pdb
  labels:
    app: {{ include "zookeeper.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: {{ .Values.pdb.zookeeper.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
