name: Publish Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CHART_PATH: .  # Default path, can be overridden in repository settings
  REPO_URL: ${{ secrets.REPO_URL }}  # Repository URL stored as a secret for security

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Use the latest version of checkout

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0  # Official Azure setup for Helm
        # with:
        #   version: '3.12.0'  # Specify the Helm version

      - name: Lint Helm Chart  # Optional step to validate the Helm chart
        run: |
          helm lint "${{ env.CHART_PATH }}"

      - name: Update Helm Dependencies
        run: |
          helm dependency update "${{ env.CHART_PATH }}"

      - name: Package Helm Chart
        run: |
          helm package "${{ env.CHART_PATH }}" -d packaged-charts/

      - name: Generate Helm Index
        run: |
          helm repo index packaged-charts/ --url "${{ env.REPO_URL }}"

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packaged-charts
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
