name: Publish Helm Chart

on:
  push:
    branches:
      - main
    # Remove the reference to ${{ env.CHART_PATH }} here; it doesn't support `env` directly
  workflow_dispatch:

env:
  CHART_PATH: "chart"  # Default value; can be overridden in repository settings
  REPO_URL: ${{ secrets.REPO_URL }}  # Repository URL stored as a secret for security

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Package Helm Chart
        run: |
          helm package "${{ env.CHART_PATH }}" -d packaged-charts/

      - name: Generate Helm Index
        run: |
          # Generate an index.yaml using the REPO_URL environment variable
          helm repo index packaged-charts/ --url "${{ env.REPO_URL }}"
          
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packaged-charts
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
